name: Deploy Next.js application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: 
          touch .env
          echo MONGO_URL="mongodb+srv://foodorderapp:62ZcsvJ6wLF0AaXI@cluster0.qpwyy.mongodb.net/food-ordering?retryWrites=true&w=majority&appName=Cluster0" >> .env
          echo NEXTAUTH_URL="http://localhost:3000/" >> .env
          echo SECRET="asdasdasd123" >> .env
          echo GOOGLE_CLIENT_ID="" >> .env
          echo GOOGLE_CLIENT_SECRET="" >> .env
          echo STRIE_SIGN_SECRET="47:00" >> .env
          echo AWS_S3_BUCKET="ben007-food-ordering" >> .env
          echo AWS_REGION="ap-southeast-2" >> .env
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> .env
          echo "AWS_ACCESS_KEY=${{ secrets.ACCESS_KEY }}" >> .env
          echo "STRIPE_SK=${{ secrets.STRIPE_SK }}" >> .env
          echo "STRIPE_PK=${{ secrets.STRIPE_PK }}" >> .env
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env && echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
      - name: Build docker image
        run: docker build -t bobbestben/food-order-app-app .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image to docker hub
        run: docker push bobbestben/food-order-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull bobbestben/food-order-app:latest
      - name: Delete old container
        run: docker rm -f food-order-app-container  
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name food-order-app-container bobbestben/food-order-app:latest 